// Traduz categorias do Pluggy/Banco MCP (inglês) para pt-BR.
const MAP: Record<string, string> = {
  "income": "Renda",
  "salary": "Salário",
  "transfers": "Transferências",
  "transfer": "Transferências",
  "same person transfer": "Entre contas",
  "pix": "Pix",
  "ted": "TED",
  "doc": "DOC",
  "withdrawal": "Saque",
  "deposit": "Depósito",
  "loans": "Empréstimos",
  "loan": "Empréstimos",
  "financing": "Financiamento",
  "investments": "Investimentos",
  "investment": "Investimentos",
  "food and drink": "Alimentação",
  "groceries": "Supermercado",
  "supermarket": "Supermercado",
  "restaurants": "Restaurantes",
  "food delivery": "Delivery",
  "shopping": "Compras",
  "online shopping": "Compras online",
  "clothing": "Vestuário",
  "electronics": "Eletrônicos",
  "transportation": "Transporte",
  "transport": "Transporte",
  "gas stations": "Combustível",
  "fuel": "Combustível",
  "ride hailing": "Apps de mobilidade",
  "public transportation": "Transporte público",
  "travel": "Viagens",
  "airlines": "Passagens aéreas",
  "lodging": "Hospedagem",
  "bills and utilities": "Contas e utilidades",
  "utilities": "Utilidades",
  "electricity": "Energia elétrica",
  "water": "Água",
  "gas": "Gás",
  "internet": "Internet",
  "telecommunications": "Telefonia e internet",
  "phone": "Telefone",
  "rent": "Aluguel",
  "mortgage": "Financiamento imobiliário",
  "housing": "Moradia",
  "healthcare": "Saúde",
  "health": "Saúde",
  "pharmacy": "Farmácia",
  "education": "Educação",
  "entertainment": "Lazer",
  "leisure": "Lazer",
  "streaming": "Streaming",
  "subscriptions": "Assinaturas",
  "services": "Serviços",
  "digital services": "Serviços digitais",
  "taxes": "Impostos",
  "insurance": "Seguros",
  "fees": "Tarifas",
  "bank fees": "Tarifas bancárias",
  "interest": "Juros",
  "credit card payment": "Pagamento de cartão",
  "credit card": "Cartão de crédito",
  "donations": "Doações",
  "pets": "Pets",
  "beauty": "Beleza",
  "gifts": "Presentes",
  "leisure and entertainment": "Lazer",
  "uncategorized": "Sem categoria",
  "other": "Outros",
  "transfer - pix": "Pix",
  "transferência entre contas": "Entre contas",
  "transfer - ted": "TED/DOC",
  "transfer - doc": "TED/DOC",
  "bookstore": "Livros",
};

export function categoryPtBr(raw: string | null | undefined): string {
  if (!raw) return "Sem categoria";
  const key = raw.trim().toLowerCase();
  return MAP[key] ?? raw; // desconhecida: mantém o original
}
